apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: echo
      image: my.harbor.cn/k8sstudy/alpine:latest
      script: |
        #!/bin/sh
        echo "Hello World"

---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: hello-task-run
spec:
  taskRef:
    name: hello