apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nettool
  name: nettool
spec:
  selector:
    matchLabels:
      app: nettool
  template:
    metadata:
      labels:
        app: nettool
    spec:
      volumes:
        - name: host
          hostPath:
            path: /
            type: Directory
      containers:
        - image: my.harbor.cn/k8sstudy/nettool:latest
          name: nettoolbox
          volumeMounts:
            - name: host
              mountPath: /host
          env:
            - name: NETTOOL_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: nettool
spec:
  type: NodePort
  selector:
    app: nettool
  ports:
    - name: nettool
      port: 80
      targetPort: 80
      nodePort: 32000
